### ISSUE TITLE
Dockerが起動しない

### ISSUE THREAD

**Issue by kajidog** [kajidog/golang-discode-bot#34]
・Dockerファイルの設定を修正
・READMEにもう少し詳しく構築手順かく

**Comment by kajidog** [comment]
```
2024-05-26 01:28:57 Executing: go mod tidy
2024-05-26 01:29:47 2024/05/25 16:29:47 KnownStructs: app.Speaker       app.Style       discordgo.Member        discordgo.User  discordgo.UserGuild     main.DiscordConfig      options.SecondInstanceData       settings.UserSettings
2024-05-26 01:29:47 time.Time
2024-05-26 01:29:47 KnownStructs: app.Speaker   app.Style       discordgo.Member        discordgo.User  discordgo.UserGuild     main.DiscordConfig      options.SecondInstanceData      settings.UserSettings
2024-05-26 01:29:47 discordgo.User
2024-05-26 01:29:47 KnownStructs: app.Speaker   app.Style       discordgo.Member        discordgo.User  discordgo.UserGuild     main.DiscordConfig      options.SecondInstanceData      settings.UserSettings
2024-05-26 01:29:47 time.Time
2024-05-26 01:29:47 KnownStructs: app.Speaker   app.Style       discordgo.Member        discordgo.User  discordgo.UserGuild     main.DiscordConfig      options.SecondInstanceData      settings.UserSettings
2024-05-26 01:29:47 time.Time
2024-05-26 01:29:47 
2024-05-26 01:30:03 Vite Server URL: http://localhost:5173/
2024-05-26 01:30:03 Running frontend DevWatcher command: 'npm run dev'
2024-05-26 01:30:46 2024/05/25 16:30:46 KnownStructs: app.Speaker       app.Style       discordgo.Member        discordgo.User  discordgo.UserGuild     main.DiscordConfig      options.SecondInstanceData       settings.UserSettings
2024-05-26 01:30:46 time.Time
2024-05-26 01:30:46 KnownStructs: app.Speaker   app.Style       discordgo.Member        discordgo.User  discordgo.UserGuild     main.DiscordConfig      options.SecondInstanceData      settings.UserSettings
2024-05-26 01:30:46 discordgo.User
2024-05-26 01:30:46 KnownStructs: app.Speaker   app.Style       discordgo.Member        discordgo.User  discordgo.UserGuild     main.DiscordConfig      options.SecondInstanceData      settings.UserSettings
2024-05-26 01:30:46 time.Time
2024-05-26 01:30:46 KnownStructs: app.Speaker   app.Style       discordgo.Member        discordgo.User  discordgo.UserGuild     main.DiscordConfig      options.SecondInstanceData      settings.UserSettings
2024-05-26 01:30:46 time.Time
2024-05-26 01:30:46 
2024-05-26 01:28:57 Wails CLI v2.8.2
2024-05-26 01:28:57 
2024-05-26 01:29:47   • Generating bindings: Done.
2024-05-26 01:29:47   • Installing frontend dependencies: Done.
2024-05-26 01:30:02   • Compiling frontend: Done.
2024-05-26 01:30:03 
2024-05-26 01:30:03 > dev
2024-05-26 01:30:03 > vite
2024-05-26 01:30:03 
2024-05-26 01:30:03 
2024-05-26 01:30:03   VITE v3.1.4  ready in 637 ms
2024-05-26 01:30:03 
2024-05-26 01:30:03   ➜  Local:   http://localhost:5173/
2024-05-26 01:30:03   ➜  Network: use --host to expose
2024-05-26 01:30:03 Building application for development...
2024-05-26 01:30:46   • Generating bindings: Done.
2024-05-26 01:31:26   • Compiling application: Done.
2024-05-26 01:31:26   • Packaging application: Done.
2024-05-26 01:31:26 
2024-05-26 01:31:26 Using DevServer URL: http://localhost:34115
2024-05-26 01:31:26 Using Frontend DevServer URL: http://localhost:5173/
2024-05-26 01:31:26 Using reload debounce setting of 100 milliseconds
2024-05-26 01:31:26 INF | Serving assets from frontend DevServer URL: http://localhost:5173/
2024-05-26 01:31:26 panic: failed to init GTK
2024-05-26 01:31:26 
2024-05-26 01:31:26 goroutine 1 [running, locked to thread]:
2024-05-26 01:31:26 github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend.func1()
2024-05-26 01:31:26     /go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.2/internal/frontend/desktop/linux/frontend.go:145 +0x307
2024-05-26 01:31:26 sync.(*Once).doSlow(0x137cfe8, 0xef6188)
2024-05-26 01:31:26     /usr/local/go/src/sync/once.go:74 +0x15a
2024-05-26 01:31:26 sync.(*Once).Do(0x137cfe8, 0xef6188)
2024-05-26 01:31:26     /usr/local/go/src/sync/once.go:65 +0x3a
2024-05-26 01:31:26 github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend({0xf3ef98, 0xc00020b230}, 0xc0000fe160, 0xc000012918, 0xc0001ad3b0, {0xf3a6a0, 0xc00007f540})
2024-05-26 01:31:26     /go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.2/internal/frontend/desktop/linux/frontend.go:136 +0x71
2024-05-26 01:31:26 github.com/wailsapp/wails/v2/internal/frontend/desktop.NewFrontend({0xf3ef98, 0xc00020b230}, 0xc0000fe160, 0xc000012918, 0xc0001ad3b0, {0xf3a6a0, 0xc00007f540})
2024-05-26 01:31:26     /go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.2/internal/frontend/desktop/desktop_linux.go:16 +0x75
2024-05-26 01:31:26 github.com/wailsapp/wails/v2/internal/app.CreateApp(0xc0000fe160)
2024-05-26 01:31:26     /go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.2/internal/app/app_dev.go:219 +0x18d8
2024-05-26 01:31:26 github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc00007b140)
2024-05-26 01:31:26     /go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.2/pkg/application/application.go:58 +0x77
2024-05-26 01:31:26 github.com/wailsapp/wails/v2.Run(0xc0000fe160)
2024-05-26 01:31:26     /go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.2/wails.go:14 +0x2f
2024-05-26 01:31:26 main.main()
2024-05-26 01:31:26     /app/main.go:26 +0x60f
2024-05-26 01:31:29 
2024-05-26 01:31:29 
2024-05-26 01:31:29 To develop in the browser and call your bound Go methods from Javascript, navigate to: http://localhost:34115
2024-05-26 01:31:38 Watching (sub)/directory: /ap
```

**Comment by kajidog** [comment]
Windowsだとどうしても解決できなかったので諦めまーす
